// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFeedsFeedIDFollowOKCode is the HTTP code returned for type DeleteFeedsFeedIDFollowOK
const DeleteFeedsFeedIDFollowOKCode int = 200

/*DeleteFeedsFeedIDFollowOK OK

swagger:response deleteFeedsFeedIdFollowOK
*/
type DeleteFeedsFeedIDFollowOK struct {
}

// NewDeleteFeedsFeedIDFollowOK creates DeleteFeedsFeedIDFollowOK with default headers values
func NewDeleteFeedsFeedIDFollowOK() *DeleteFeedsFeedIDFollowOK {

	return &DeleteFeedsFeedIDFollowOK{}
}

// WriteResponse to the client
func (o *DeleteFeedsFeedIDFollowOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
