// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteFeedsFeedIDFollowHandlerFunc turns a function with the right signature into a delete feeds feed ID follow handler
type DeleteFeedsFeedIDFollowHandlerFunc func(DeleteFeedsFeedIDFollowParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFeedsFeedIDFollowHandlerFunc) Handle(params DeleteFeedsFeedIDFollowParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteFeedsFeedIDFollowHandler interface for that can handle valid delete feeds feed ID follow params
type DeleteFeedsFeedIDFollowHandler interface {
	Handle(DeleteFeedsFeedIDFollowParams, interface{}) middleware.Responder
}

// NewDeleteFeedsFeedIDFollow creates a new http.Handler for the delete feeds feed ID follow operation
func NewDeleteFeedsFeedIDFollow(ctx *middleware.Context, handler DeleteFeedsFeedIDFollowHandler) *DeleteFeedsFeedIDFollow {
	return &DeleteFeedsFeedIDFollow{Context: ctx, Handler: handler}
}

/*DeleteFeedsFeedIDFollow swagger:route DELETE /feeds/{feedId}/follow feeds deleteFeedsFeedIdFollow

DeleteFeedsFeedIDFollow delete feeds feed ID follow API

*/
type DeleteFeedsFeedIDFollow struct {
	Context *middleware.Context
	Handler DeleteFeedsFeedIDFollowHandler
}

func (o *DeleteFeedsFeedIDFollow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteFeedsFeedIDFollowParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
