// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteFeedsFeedIDJoinHandlerFunc turns a function with the right signature into a delete feeds feed ID join handler
type DeleteFeedsFeedIDJoinHandlerFunc func(DeleteFeedsFeedIDJoinParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteFeedsFeedIDJoinHandlerFunc) Handle(params DeleteFeedsFeedIDJoinParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteFeedsFeedIDJoinHandler interface for that can handle valid delete feeds feed ID join params
type DeleteFeedsFeedIDJoinHandler interface {
	Handle(DeleteFeedsFeedIDJoinParams, interface{}) middleware.Responder
}

// NewDeleteFeedsFeedIDJoin creates a new http.Handler for the delete feeds feed ID join operation
func NewDeleteFeedsFeedIDJoin(ctx *middleware.Context, handler DeleteFeedsFeedIDJoinHandler) *DeleteFeedsFeedIDJoin {
	return &DeleteFeedsFeedIDJoin{Context: ctx, Handler: handler}
}

/*DeleteFeedsFeedIDJoin swagger:route DELETE /feeds/{feedId}/join feeds deleteFeedsFeedIdJoin

DeleteFeedsFeedIDJoin delete feeds feed ID join API

*/
type DeleteFeedsFeedIDJoin struct {
	Context *middleware.Context
	Handler DeleteFeedsFeedIDJoinHandler
}

func (o *DeleteFeedsFeedIDJoin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteFeedsFeedIDJoinParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
