// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFeedsFeedIDJoinUserIDOKCode is the HTTP code returned for type DeleteFeedsFeedIDJoinUserIDOK
const DeleteFeedsFeedIDJoinUserIDOKCode int = 200

/*DeleteFeedsFeedIDJoinUserIDOK OK

swagger:response deleteFeedsFeedIdJoinUserIdOK
*/
type DeleteFeedsFeedIDJoinUserIDOK struct {
}

// NewDeleteFeedsFeedIDJoinUserIDOK creates DeleteFeedsFeedIDJoinUserIDOK with default headers values
func NewDeleteFeedsFeedIDJoinUserIDOK() *DeleteFeedsFeedIDJoinUserIDOK {

	return &DeleteFeedsFeedIDJoinUserIDOK{}
}

// WriteResponse to the client
func (o *DeleteFeedsFeedIDJoinUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
