// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFeedsFeedIDOKCode is the HTTP code returned for type DeleteFeedsFeedIDOK
const DeleteFeedsFeedIDOKCode int = 200

/*DeleteFeedsFeedIDOK OK

swagger:response deleteFeedsFeedIdOK
*/
type DeleteFeedsFeedIDOK struct {
}

// NewDeleteFeedsFeedIDOK creates DeleteFeedsFeedIDOK with default headers values
func NewDeleteFeedsFeedIDOK() *DeleteFeedsFeedIDOK {

	return &DeleteFeedsFeedIDOK{}
}

// WriteResponse to the client
func (o *DeleteFeedsFeedIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
