// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteFeedsFeedIDJoinOKCode is the HTTP code returned for type DeleteFeedsFeedIDJoinOK
const DeleteFeedsFeedIDJoinOKCode int = 200

/*DeleteFeedsFeedIDJoinOK OK

swagger:response deleteFeedsFeedIdJoinOK
*/
type DeleteFeedsFeedIDJoinOK struct {
}

// NewDeleteFeedsFeedIDJoinOK creates DeleteFeedsFeedIDJoinOK with default headers values
func NewDeleteFeedsFeedIDJoinOK() *DeleteFeedsFeedIDJoinOK {

	return &DeleteFeedsFeedIDJoinOK{}
}

// WriteResponse to the client
func (o *DeleteFeedsFeedIDJoinOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
