// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// GetFeedsOKCode is the HTTP code returned for type GetFeedsOK
const GetFeedsOKCode int = 200

/*GetFeedsOK OK

swagger:response getFeedsOK
*/
type GetFeedsOK struct {

	/*
	  In: Body
	*/
	Payload models.Feeds `json:"body,omitempty"`
}

// NewGetFeedsOK creates GetFeedsOK with default headers values
func NewGetFeedsOK() *GetFeedsOK {

	return &GetFeedsOK{}
}

// WithPayload adds the payload to the get feeds o k response
func (o *GetFeedsOK) WithPayload(payload models.Feeds) *GetFeedsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get feeds o k response
func (o *GetFeedsOK) SetPayload(payload models.Feeds) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFeedsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Feeds{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
