// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostFeedsFeedIDJoinUserIDOKCode is the HTTP code returned for type PostFeedsFeedIDJoinUserIDOK
const PostFeedsFeedIDJoinUserIDOKCode int = 200

/*PostFeedsFeedIDJoinUserIDOK OK

swagger:response postFeedsFeedIdJoinUserIdOK
*/
type PostFeedsFeedIDJoinUserIDOK struct {
}

// NewPostFeedsFeedIDJoinUserIDOK creates PostFeedsFeedIDJoinUserIDOK with default headers values
func NewPostFeedsFeedIDJoinUserIDOK() *PostFeedsFeedIDJoinUserIDOK {

	return &PostFeedsFeedIDJoinUserIDOK{}
}

// WriteResponse to the client
func (o *PostFeedsFeedIDJoinUserIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
