// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostFeedsFeedIDFollowHandlerFunc turns a function with the right signature into a post feeds feed ID follow handler
type PostFeedsFeedIDFollowHandlerFunc func(PostFeedsFeedIDFollowParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFeedsFeedIDFollowHandlerFunc) Handle(params PostFeedsFeedIDFollowParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostFeedsFeedIDFollowHandler interface for that can handle valid post feeds feed ID follow params
type PostFeedsFeedIDFollowHandler interface {
	Handle(PostFeedsFeedIDFollowParams, interface{}) middleware.Responder
}

// NewPostFeedsFeedIDFollow creates a new http.Handler for the post feeds feed ID follow operation
func NewPostFeedsFeedIDFollow(ctx *middleware.Context, handler PostFeedsFeedIDFollowHandler) *PostFeedsFeedIDFollow {
	return &PostFeedsFeedIDFollow{Context: ctx, Handler: handler}
}

/*PostFeedsFeedIDFollow swagger:route POST /feeds/{feedId}/follow feeds postFeedsFeedIdFollow

PostFeedsFeedIDFollow post feeds feed ID follow API

*/
type PostFeedsFeedIDFollow struct {
	Context *middleware.Context
	Handler PostFeedsFeedIDFollowHandler
}

func (o *PostFeedsFeedIDFollow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostFeedsFeedIDFollowParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
