// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostFeedsHandlerFunc turns a function with the right signature into a post feeds handler
type PostFeedsHandlerFunc func(PostFeedsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFeedsHandlerFunc) Handle(params PostFeedsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostFeedsHandler interface for that can handle valid post feeds params
type PostFeedsHandler interface {
	Handle(PostFeedsParams, interface{}) middleware.Responder
}

// NewPostFeeds creates a new http.Handler for the post feeds operation
func NewPostFeeds(ctx *middleware.Context, handler PostFeedsHandler) *PostFeeds {
	return &PostFeeds{Context: ctx, Handler: handler}
}

/*PostFeeds swagger:route POST /feeds feeds postFeeds

PostFeeds post feeds API

*/
type PostFeeds struct {
	Context *middleware.Context
	Handler PostFeedsHandler
}

func (o *PostFeeds) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostFeedsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
