// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostFeedsFeedIDJoinHandlerFunc turns a function with the right signature into a post feeds feed ID join handler
type PostFeedsFeedIDJoinHandlerFunc func(PostFeedsFeedIDJoinParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFeedsFeedIDJoinHandlerFunc) Handle(params PostFeedsFeedIDJoinParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostFeedsFeedIDJoinHandler interface for that can handle valid post feeds feed ID join params
type PostFeedsFeedIDJoinHandler interface {
	Handle(PostFeedsFeedIDJoinParams, interface{}) middleware.Responder
}

// NewPostFeedsFeedIDJoin creates a new http.Handler for the post feeds feed ID join operation
func NewPostFeedsFeedIDJoin(ctx *middleware.Context, handler PostFeedsFeedIDJoinHandler) *PostFeedsFeedIDJoin {
	return &PostFeedsFeedIDJoin{Context: ctx, Handler: handler}
}

/*PostFeedsFeedIDJoin swagger:route POST /feeds/{feedId}/join feeds postFeedsFeedIdJoin

PostFeedsFeedIDJoin post feeds feed ID join API

*/
type PostFeedsFeedIDJoin struct {
	Context *middleware.Context
	Handler PostFeedsFeedIDJoinHandler
}

func (o *PostFeedsFeedIDJoin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostFeedsFeedIDJoinParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
