// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PostFeedsOKCode is the HTTP code returned for type PostFeedsOK
const PostFeedsOKCode int = 200

/*PostFeedsOK OK

swagger:response postFeedsOK
*/
type PostFeedsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Feed `json:"body,omitempty"`
}

// NewPostFeedsOK creates PostFeedsOK with default headers values
func NewPostFeedsOK() *PostFeedsOK {

	return &PostFeedsOK{}
}

// WithPayload adds the payload to the post feeds o k response
func (o *PostFeedsOK) WithPayload(payload *models.Feed) *PostFeedsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post feeds o k response
func (o *PostFeedsOK) SetPayload(payload *models.Feed) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFeedsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
