// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostFeedsFeedIDJoinUserIDHandlerFunc turns a function with the right signature into a post feeds feed ID join user ID handler
type PostFeedsFeedIDJoinUserIDHandlerFunc func(PostFeedsFeedIDJoinUserIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFeedsFeedIDJoinUserIDHandlerFunc) Handle(params PostFeedsFeedIDJoinUserIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostFeedsFeedIDJoinUserIDHandler interface for that can handle valid post feeds feed ID join user ID params
type PostFeedsFeedIDJoinUserIDHandler interface {
	Handle(PostFeedsFeedIDJoinUserIDParams, interface{}) middleware.Responder
}

// NewPostFeedsFeedIDJoinUserID creates a new http.Handler for the post feeds feed ID join user ID operation
func NewPostFeedsFeedIDJoinUserID(ctx *middleware.Context, handler PostFeedsFeedIDJoinUserIDHandler) *PostFeedsFeedIDJoinUserID {
	return &PostFeedsFeedIDJoinUserID{Context: ctx, Handler: handler}
}

/*PostFeedsFeedIDJoinUserID swagger:route POST /feeds/{feedId}/join/{userId} feeds postFeedsFeedIdJoinUserId

PostFeedsFeedIDJoinUserID post feeds feed ID join user ID API

*/
type PostFeedsFeedIDJoinUserID struct {
	Context *middleware.Context
	Handler PostFeedsFeedIDJoinUserIDHandler
}

func (o *PostFeedsFeedIDJoinUserID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostFeedsFeedIDJoinUserIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
