// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostFeedsFeedIDJoinUserIDParams creates a new PostFeedsFeedIDJoinUserIDParams object
// no default values defined in spec.
func NewPostFeedsFeedIDJoinUserIDParams() PostFeedsFeedIDJoinUserIDParams {

	return PostFeedsFeedIDJoinUserIDParams{}
}

// PostFeedsFeedIDJoinUserIDParams contains all the bound params for the post feeds feed ID join user ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostFeedsFeedIDJoinUserID
type PostFeedsFeedIDJoinUserIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	FeedID uint64
	/*
	  Required: true
	  In: path
	*/
	UserID uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostFeedsFeedIDJoinUserIDParams() beforehand.
func (o *PostFeedsFeedIDJoinUserIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rFeedID, rhkFeedID, _ := route.Params.GetOK("feedId")
	if err := o.bindFeedID(rFeedID, rhkFeedID, route.Formats); err != nil {
		res = append(res, err)
	}

	rUserID, rhkUserID, _ := route.Params.GetOK("userId")
	if err := o.bindUserID(rUserID, rhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFeedID binds and validates parameter FeedID from path.
func (o *PostFeedsFeedIDJoinUserIDParams) bindFeedID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("feedId", "path", "uint64", raw)
	}
	o.FeedID = value

	return nil
}

// bindUserID binds and validates parameter UserID from path.
func (o *PostFeedsFeedIDJoinUserIDParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("userId", "path", "uint64", raw)
	}
	o.UserID = value

	return nil
}
