// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PutFeedsFeedIDOKCode is the HTTP code returned for type PutFeedsFeedIDOK
const PutFeedsFeedIDOKCode int = 200

/*PutFeedsFeedIDOK OK

swagger:response putFeedsFeedIdOK
*/
type PutFeedsFeedIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Feed `json:"body,omitempty"`
}

// NewPutFeedsFeedIDOK creates PutFeedsFeedIDOK with default headers values
func NewPutFeedsFeedIDOK() *PutFeedsFeedIDOK {

	return &PutFeedsFeedIDOK{}
}

// WithPayload adds the payload to the put feeds feed Id o k response
func (o *PutFeedsFeedIDOK) WithPayload(payload *models.Feed) *PutFeedsFeedIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put feeds feed Id o k response
func (o *PutFeedsFeedIDOK) SetPayload(payload *models.Feed) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutFeedsFeedIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
