// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutFeedsFeedIDHandlerFunc turns a function with the right signature into a put feeds feed ID handler
type PutFeedsFeedIDHandlerFunc func(PutFeedsFeedIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutFeedsFeedIDHandlerFunc) Handle(params PutFeedsFeedIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutFeedsFeedIDHandler interface for that can handle valid put feeds feed ID params
type PutFeedsFeedIDHandler interface {
	Handle(PutFeedsFeedIDParams, interface{}) middleware.Responder
}

// NewPutFeedsFeedID creates a new http.Handler for the put feeds feed ID operation
func NewPutFeedsFeedID(ctx *middleware.Context, handler PutFeedsFeedIDHandler) *PutFeedsFeedID {
	return &PutFeedsFeedID{Context: ctx, Handler: handler}
}

/*PutFeedsFeedID swagger:route PUT /feeds/{feedId} feeds putFeedsFeedId

PutFeedsFeedID put feeds feed ID API

*/
type PutFeedsFeedID struct {
	Context *middleware.Context
	Handler PutFeedsFeedIDHandler
}

func (o *PutFeedsFeedID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutFeedsFeedIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
