// Code generated by go-swagger; DO NOT EDIT.

package feeds

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "morg/models"
)

// NewPutFeedsFeedIDParams creates a new PutFeedsFeedIDParams object
// no default values defined in spec.
func NewPutFeedsFeedIDParams() PutFeedsFeedIDParams {

	return PutFeedsFeedIDParams{}
}

// PutFeedsFeedIDParams contains all the bound params for the put feeds feed ID operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutFeedsFeedID
type PutFeedsFeedIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Body *models.FeedUpdate
	/*
	  Required: true
	  In: path
	*/
	FeedID uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutFeedsFeedIDParams() beforehand.
func (o *PutFeedsFeedIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.FeedUpdate
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	rFeedID, rhkFeedID, _ := route.Params.GetOK("feedId")
	if err := o.bindFeedID(rFeedID, rhkFeedID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFeedID binds and validates parameter FeedID from path.
func (o *PutFeedsFeedIDParams) bindFeedID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("feedId", "path", "uint64", raw)
	}
	o.FeedID = value

	return nil
}
