// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PostRegistrationOKCode is the HTTP code returned for type PostRegistrationOK
const PostRegistrationOKCode int = 200

/*PostRegistrationOK OK

swagger:response postRegistrationOK
*/
type PostRegistrationOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewPostRegistrationOK creates PostRegistrationOK with default headers values
func NewPostRegistrationOK() *PostRegistrationOK {

	return &PostRegistrationOK{}
}

// WithPayload adds the payload to the post registration o k response
func (o *PostRegistrationOK) WithPayload(payload *models.Profile) *PostRegistrationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post registration o k response
func (o *PostRegistrationOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegistrationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
