// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostRegistrationHandlerFunc turns a function with the right signature into a post registration handler
type PostRegistrationHandlerFunc func(PostRegistrationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostRegistrationHandlerFunc) Handle(params PostRegistrationParams) middleware.Responder {
	return fn(params)
}

// PostRegistrationHandler interface for that can handle valid post registration params
type PostRegistrationHandler interface {
	Handle(PostRegistrationParams) middleware.Responder
}

// NewPostRegistration creates a new http.Handler for the post registration operation
func NewPostRegistration(ctx *middleware.Context, handler PostRegistrationHandler) *PostRegistration {
	return &PostRegistration{Context: ctx, Handler: handler}
}

/*PostRegistration swagger:route POST /registration auth postRegistration

PostRegistration post registration API

*/
type PostRegistration struct {
	Context *middleware.Context
	Handler PostRegistrationHandler
}

func (o *PostRegistration) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostRegistrationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
