// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Minter.org Hub
Description


    Schemes:
      http
      https
    Host: minter.org
    BasePath: /v1
    Version: 1.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
