// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Description",
    "title": "Minter.org Hub",
    "version": "1.1.0"
  },
  "host": "minter.org",
  "basePath": "/v1",
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/offsetParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          },
          {
            "type": "boolean",
            "default": false,
            "name": "followed",
            "in": "query"
          },
          {
            "enum": [
              "date",
              "comments",
              "rating"
            ],
            "type": "string",
            "default": "date",
            "name": "sortBy",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "tag",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Articles"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ArticleCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Article"
            }
          }
        }
      }
    },
    "/articles/{articleId}": {
      "get": {
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Articles"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ArticleUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Article"
            }
          }
        }
      }
    },
    "/articles/{articleId}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/offsetParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Comments"
            }
          }
        }
      }
    },
    "/articles/{articleId}/vote": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              -1,
              0,
              1
            ],
            "type": "integer",
            "format": "int64",
            "name": "vote",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      }
    },
    "/comments": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CommentCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Comment"
            }
          }
        }
      }
    },
    "/comments/{commentId}": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "commentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Articles"
            }
          }
        }
      }
    },
    "/comments/{commentId}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "name": "commentId",
            "in": "path",
            "required": true
          },
          {
            "$ref": "#/parameters/offsetParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Comments"
            }
          }
        }
      }
    },
    "/comments/{commentId}/vote": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "commentId",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              -1,
              0,
              1
            ],
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "vote",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      }
    },
    "/feeds": {
      "get": {
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/offsetParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Feeds"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/FeedCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      }
    },
    "/feeds/{feedId}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/FeedUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/feeds/{feedId}/follow": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/feeds/{feedId}/join": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/feeds/{feedId}/join/{userId}": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Login"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me": {
      "get": {
        "tags": [
          "me"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/notifications": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "enum": [
              "requests",
              "comments",
              "replies",
              "follows"
            ],
            "type": "string",
            "name": "type",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Notifications"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "пометить уведомления как прочитанные",
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "type": "integer",
              "format": "uint64"
            },
            "name": "type",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/me/settings": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProfileUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/settings/notifications": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NotificationSettings"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/settings/password": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PasswordUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/tags": {
      "get": {
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/offsetParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "/profiles": {
      "get": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "$ref": "#/parameters/offsetParam"
          },
          {
            "$ref": "#/parameters/limitParam"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profiles"
            }
          }
        }
      }
    },
    "/profiles/{username}": {
      "get": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileFull"
            }
          }
        }
      }
    },
    "/profiles/{username}/star": {
      "post": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileFull"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileFull"
            }
          }
        }
      }
    },
    "/registration": {
      "post": {
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProfileCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Article": {
      "type": "object",
      "required": [
        "id",
        "title",
        "description",
        "tags",
        "author",
        "voted",
        "voites",
        "comments",
        "createdAt",
        "imageUrl"
      ],
      "properties": {
        "author": {
          "$ref": "#/definitions/Author"
        },
        "comments": {
          "type": "integer",
          "format": "uint64",
          "default": 0
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "title": {
          "type": "string"
        },
        "voites": {
          "type": "integer",
          "format": "int64",
          "default": 0,
          "example": 15
        },
        "voted": {
          "type": "integer",
          "format": "int32",
          "default": 0,
          "enum": [
            1,
            0,
            -1
          ]
        }
      }
    },
    "ArticleCreate": {
      "type": "object",
      "required": [
        "title",
        "description",
        "tags",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "maximum": 3,
          "uniqueItems": true,
          "items": {
            "type": "integer",
            "format": "uint64"
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "ArticleUpdate": {
      "type": "object",
      "required": [
        "title",
        "description",
        "tags"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "maximum": 3,
          "uniqueItems": true,
          "items": {
            "type": "integer",
            "format": "uint64"
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Articles": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Article"
      }
    },
    "Author": {
      "type": "object",
      "required": [
        "id",
        "username",
        "imageUrl",
        "kyc"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "kyc": {
          "type": "boolean"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Authors": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Author"
      }
    },
    "Comment": {
      "type": "object",
      "required": [
        "id",
        "body",
        "articleId",
        "author",
        "createdAt",
        "parentId"
      ],
      "properties": {
        "articleId": {
          "type": "integer",
          "format": "uint64"
        },
        "author": {
          "$ref": "#/definitions/Author"
        },
        "body": {
          "type": "string"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "parentId": {
          "type": "integer",
          "format": "uint64",
          "default": 0
        },
        "voites": {
          "type": "integer",
          "format": "int64",
          "default": 0,
          "example": -2
        }
      }
    },
    "CommentCreate": {
      "type": "object",
      "required": [
        "articleId",
        "body"
      ],
      "properties": {
        "articleId": {
          "type": "integer",
          "format": "uint64"
        },
        "body": {
          "type": "string"
        },
        "parentId": {
          "description": "id коментария, на котрый отвечает",
          "type": "integer",
          "format": "uint64",
          "default": 0
        }
      }
    },
    "Comments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Comment"
      }
    },
    "Feed": {
      "type": "object",
      "required": [
        "id",
        "name",
        "description",
        "owner",
        "members",
        "joined",
        "followed",
        "followersCount",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "followed": {
          "type": "boolean"
        },
        "followersCount": {
          "type": "integer",
          "format": "uint64",
          "default": 0
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "joined": {
          "type": "boolean"
        },
        "members": {
          "$ref": "#/definitions/Authors"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "$ref": "#/definitions/Author"
        }
      }
    },
    "FeedCreate": {
      "type": "object",
      "required": [
        "name",
        "description",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "FeedUpdate": {
      "type": "object",
      "required": [
        "name",
        "description",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Feeds": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Feed"
      }
    },
    "Login": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "reCAPTCHA": {
          "description": "reCAPTCHA v3",
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Notification": {
      "type": "object",
      "required": [
        "user",
        "typeActivity",
        "meta",
        "subjectId",
        "subjectText",
        "createdAt"
      ],
      "properties": {
        "createdAt": {
          "description": "data for create link",
          "type": "string",
          "format": "date-time"
        },
        "meta": {
          "type": "object",
          "additionalProperties": true
        },
        "subjectId": {
          "type": "integer",
          "format": "uint64"
        },
        "subjectText": {
          "type": "string"
        },
        "typeActivity": {
          "type": "string",
          "enum": [
            "requests",
            "comments",
            "replies",
            "follows"
          ]
        },
        "user": {
          "$ref": "#/definitions/Author"
        }
      }
    },
    "NotificationSettings": {
      "type": "object",
      "required": [
        "requests",
        "comments",
        "follows"
      ],
      "properties": {
        "comments": {
          "type": "boolean"
        },
        "follows": {
          "type": "boolean"
        },
        "requests": {
          "type": "boolean"
        }
      }
    },
    "Notifications": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Notification"
      }
    },
    "PasswordUpdate": {
      "type": "object",
      "required": [
        "oldPassword",
        "newPassword"
      ],
      "properties": {
        "newPassword": {
          "type": "string",
          "minLength": 6
        },
        "oldPassword": {
          "type": "string"
        }
      }
    },
    "Profile": {
      "type": "object",
      "required": [
        "id",
        "username",
        "name",
        "email",
        "imageUrl",
        "notifications",
        "token"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "notifications": {
          "$ref": "#/definitions/Notification"
        },
        "token": {
          "type": "string",
          "example": "jwt"
        },
        "username": {
          "type": "string",
          "maxLength": 18,
          "minLength": 6
        }
      }
    },
    "ProfileCreate": {
      "type": "object",
      "required": [
        "username",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "minLength": 6
        },
        "reCAPTCHA": {
          "description": "reCAPTCHA v3",
          "type": "string"
        },
        "username": {
          "type": "string",
          "minLength": 6
        }
      }
    },
    "ProfileFull": {
      "type": "object",
      "required": [
        "id",
        "username",
        "name",
        "bio",
        "imageUrl",
        "favorited",
        "stars",
        "owner",
        "member"
      ],
      "properties": {
        "bio": {
          "type": "string"
        },
        "favorited": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "member": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "stars": {
          "type": "integer",
          "format": "uint32"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "ProfileUpdate": {
      "type": "object",
      "required": [
        "username",
        "name",
        "email",
        "bio",
        "imageUrl"
      ],
      "properties": {
        "bio": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Profiles": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Profile"
      }
    }
  },
  "parameters": {
    "limitParam": {
      "type": "integer",
      "format": "uint64",
      "default": 0,
      "description": "The number of items to skip before starting to collect the result set (default is 0)",
      "name": "offset",
      "in": "query",
      "allowEmptyValue": true
    },
    "offsetParam": {
      "type": "integer",
      "format": "uint64",
      "default": 20,
      "description": "The numbers of items to return (default is 20)",
      "name": "limit",
      "in": "query",
      "allowEmptyValue": true
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Description",
    "title": "Minter.org Hub",
    "version": "1.1.0"
  },
  "host": "minter.org",
  "basePath": "/v1",
  "paths": {
    "/articles": {
      "get": {
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "default": 20,
            "description": "The numbers of items to return (default is 20)",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set (default is 0)",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "boolean",
            "default": false,
            "name": "followed",
            "in": "query"
          },
          {
            "enum": [
              "date",
              "comments",
              "rating"
            ],
            "type": "string",
            "default": "date",
            "name": "sortBy",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "name": "tag",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Articles"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ArticleCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Article"
            }
          }
        }
      }
    },
    "/articles/{articleId}": {
      "get": {
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Articles"
            }
          }
        }
      },
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ArticleUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Article"
            }
          }
        }
      }
    },
    "/articles/{articleId}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 20,
            "description": "The numbers of items to return (default is 20)",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set (default is 0)",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Comments"
            }
          }
        }
      }
    },
    "/articles/{articleId}/vote": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "articles"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "articleId",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              -1,
              0,
              1
            ],
            "type": "integer",
            "format": "int64",
            "name": "vote",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      }
    },
    "/comments": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CommentCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Comment"
            }
          }
        }
      }
    },
    "/comments/{commentId}": {
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "commentId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Articles"
            }
          }
        }
      }
    },
    "/comments/{commentId}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "name": "commentId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 20,
            "description": "The numbers of items to return (default is 20)",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set (default is 0)",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Comments"
            }
          }
        }
      }
    },
    "/comments/{commentId}/vote": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "comments"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "commentId",
            "in": "path",
            "required": true
          },
          {
            "enum": [
              -1,
              0,
              1
            ],
            "type": "integer",
            "format": "int64",
            "default": 0,
            "name": "vote",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        }
      }
    },
    "/feeds": {
      "get": {
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "default": 20,
            "description": "The numbers of items to return (default is 20)",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set (default is 0)",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Feeds"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/FeedCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      }
    },
    "/feeds/{feedId}": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/FeedUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Feed"
            }
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/feeds/{feedId}/follow": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/feeds/{feedId}/join": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/feeds/{feedId}/join/{userId}": {
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "feeds"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "name": "feedId",
            "in": "path",
            "required": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "name": "userId",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Login"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me": {
      "get": {
        "tags": [
          "me"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/notifications": {
      "get": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "enum": [
              "requests",
              "comments",
              "replies",
              "follows"
            ],
            "type": "string",
            "name": "type",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Notifications"
            }
          }
        }
      },
      "post": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "description": "пометить уведомления как прочитанные",
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "uniqueItems": true,
            "type": "array",
            "items": {
              "type": "integer",
              "format": "uint64"
            },
            "name": "type",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/me/settings": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProfileUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/settings/notifications": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/NotificationSettings"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/settings/password": {
      "put": {
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/PasswordUpdate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    },
    "/me/tags": {
      "get": {
        "tags": [
          "me"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "default": 20,
            "description": "The numbers of items to return (default is 20)",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set (default is 0)",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "/profiles": {
      "get": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "integer",
            "format": "uint64",
            "default": 20,
            "description": "The numbers of items to return (default is 20)",
            "name": "limit",
            "in": "query",
            "allowEmptyValue": true
          },
          {
            "type": "integer",
            "format": "uint64",
            "default": 0,
            "description": "The number of items to skip before starting to collect the result set (default is 0)",
            "name": "offset",
            "in": "query",
            "allowEmptyValue": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profiles"
            }
          }
        }
      }
    },
    "/profiles/{username}": {
      "get": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileFull"
            }
          }
        }
      }
    },
    "/profiles/{username}/star": {
      "post": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileFull"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "profile"
        ],
        "parameters": [
          {
            "type": "string",
            "name": "username",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/ProfileFull"
            }
          }
        }
      }
    },
    "/registration": {
      "post": {
        "tags": [
          "auth"
        ],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProfileCreate"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Profile"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Article": {
      "type": "object",
      "required": [
        "id",
        "title",
        "description",
        "tags",
        "author",
        "voted",
        "voites",
        "comments",
        "createdAt",
        "imageUrl"
      ],
      "properties": {
        "author": {
          "$ref": "#/definitions/Author"
        },
        "comments": {
          "type": "integer",
          "format": "uint64",
          "default": 0
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "title": {
          "type": "string"
        },
        "voites": {
          "type": "integer",
          "format": "int64",
          "default": 0,
          "example": 15
        },
        "voted": {
          "type": "integer",
          "format": "int32",
          "default": 0,
          "enum": [
            1,
            0,
            -1
          ]
        }
      }
    },
    "ArticleCreate": {
      "type": "object",
      "required": [
        "title",
        "description",
        "tags",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "maximum": 3,
          "uniqueItems": true,
          "items": {
            "type": "integer",
            "format": "uint64"
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "ArticleUpdate": {
      "type": "object",
      "required": [
        "title",
        "description",
        "tags"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "tags": {
          "type": "array",
          "maximum": 3,
          "uniqueItems": true,
          "items": {
            "type": "integer",
            "format": "uint64"
          }
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Articles": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Article"
      }
    },
    "Author": {
      "type": "object",
      "required": [
        "id",
        "username",
        "imageUrl",
        "kyc"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "kyc": {
          "type": "boolean"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Authors": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Author"
      }
    },
    "Comment": {
      "type": "object",
      "required": [
        "id",
        "body",
        "articleId",
        "author",
        "createdAt",
        "parentId"
      ],
      "properties": {
        "articleId": {
          "type": "integer",
          "format": "uint64"
        },
        "author": {
          "$ref": "#/definitions/Author"
        },
        "body": {
          "type": "string"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "parentId": {
          "type": "integer",
          "format": "uint64",
          "default": 0
        },
        "voites": {
          "type": "integer",
          "format": "int64",
          "default": 0,
          "example": -2
        }
      }
    },
    "CommentCreate": {
      "type": "object",
      "required": [
        "articleId",
        "body"
      ],
      "properties": {
        "articleId": {
          "type": "integer",
          "format": "uint64"
        },
        "body": {
          "type": "string"
        },
        "parentId": {
          "description": "id коментария, на котрый отвечает",
          "type": "integer",
          "format": "uint64",
          "default": 0
        }
      }
    },
    "Comments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Comment"
      }
    },
    "Feed": {
      "type": "object",
      "required": [
        "id",
        "name",
        "description",
        "owner",
        "members",
        "joined",
        "followed",
        "followersCount",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "followed": {
          "type": "boolean"
        },
        "followersCount": {
          "type": "integer",
          "format": "uint64",
          "default": 0
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "joined": {
          "type": "boolean"
        },
        "members": {
          "$ref": "#/definitions/Authors"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "$ref": "#/definitions/Author"
        }
      }
    },
    "FeedCreate": {
      "type": "object",
      "required": [
        "name",
        "description",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "FeedUpdate": {
      "type": "object",
      "required": [
        "name",
        "description",
        "imageUrl"
      ],
      "properties": {
        "description": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Feeds": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Feed"
      }
    },
    "Login": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "password": {
          "type": "string"
        },
        "reCAPTCHA": {
          "description": "reCAPTCHA v3",
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Notification": {
      "type": "object",
      "required": [
        "user",
        "typeActivity",
        "meta",
        "subjectId",
        "subjectText",
        "createdAt"
      ],
      "properties": {
        "createdAt": {
          "description": "data for create link",
          "type": "string",
          "format": "date-time"
        },
        "meta": {
          "type": "object",
          "additionalProperties": true
        },
        "subjectId": {
          "type": "integer",
          "format": "uint64"
        },
        "subjectText": {
          "type": "string"
        },
        "typeActivity": {
          "type": "string",
          "enum": [
            "requests",
            "comments",
            "replies",
            "follows"
          ]
        },
        "user": {
          "$ref": "#/definitions/Author"
        }
      }
    },
    "NotificationSettings": {
      "type": "object",
      "required": [
        "requests",
        "comments",
        "follows"
      ],
      "properties": {
        "comments": {
          "type": "boolean"
        },
        "follows": {
          "type": "boolean"
        },
        "requests": {
          "type": "boolean"
        }
      }
    },
    "Notifications": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Notification"
      }
    },
    "PasswordUpdate": {
      "type": "object",
      "required": [
        "oldPassword",
        "newPassword"
      ],
      "properties": {
        "newPassword": {
          "type": "string",
          "minLength": 6
        },
        "oldPassword": {
          "type": "string"
        }
      }
    },
    "Profile": {
      "type": "object",
      "required": [
        "id",
        "username",
        "name",
        "email",
        "imageUrl",
        "notifications",
        "token"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "notifications": {
          "$ref": "#/definitions/Notification"
        },
        "token": {
          "type": "string",
          "example": "jwt"
        },
        "username": {
          "type": "string",
          "maxLength": 18,
          "minLength": 6
        }
      }
    },
    "ProfileCreate": {
      "type": "object",
      "required": [
        "username",
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "minLength": 6
        },
        "reCAPTCHA": {
          "description": "reCAPTCHA v3",
          "type": "string"
        },
        "username": {
          "type": "string",
          "minLength": 6
        }
      }
    },
    "ProfileFull": {
      "type": "object",
      "required": [
        "id",
        "username",
        "name",
        "bio",
        "imageUrl",
        "favorited",
        "stars",
        "owner",
        "member"
      ],
      "properties": {
        "bio": {
          "type": "string"
        },
        "favorited": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "uint64"
        },
        "imageUrl": {
          "type": "string"
        },
        "member": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "string"
          }
        },
        "stars": {
          "type": "integer",
          "format": "uint32"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "ProfileUpdate": {
      "type": "object",
      "required": [
        "username",
        "name",
        "email",
        "bio",
        "imageUrl"
      ],
      "properties": {
        "bio": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "imageUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "Profiles": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Profile"
      }
    }
  },
  "parameters": {
    "limitParam": {
      "type": "integer",
      "format": "uint64",
      "default": 0,
      "description": "The number of items to skip before starting to collect the result set (default is 0)",
      "name": "offset",
      "in": "query",
      "allowEmptyValue": true
    },
    "offsetParam": {
      "type": "integer",
      "format": "uint64",
      "default": 20,
      "description": "The numbers of items to return (default is 20)",
      "name": "limit",
      "in": "query",
      "allowEmptyValue": true
    }
  },
  "securityDefinitions": {
    "bearerAuth": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
