// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// GetMeNotificationsOKCode is the HTTP code returned for type GetMeNotificationsOK
const GetMeNotificationsOKCode int = 200

/*GetMeNotificationsOK OK

swagger:response getMeNotificationsOK
*/
type GetMeNotificationsOK struct {

	/*
	  In: Body
	*/
	Payload models.Notifications `json:"body,omitempty"`
}

// NewGetMeNotificationsOK creates GetMeNotificationsOK with default headers values
func NewGetMeNotificationsOK() *GetMeNotificationsOK {

	return &GetMeNotificationsOK{}
}

// WithPayload adds the payload to the get me notifications o k response
func (o *GetMeNotificationsOK) WithPayload(payload models.Notifications) *GetMeNotificationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get me notifications o k response
func (o *GetMeNotificationsOK) SetPayload(payload models.Notifications) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeNotificationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Notifications{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
