// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetMeTagsHandlerFunc turns a function with the right signature into a get me tags handler
type GetMeTagsHandlerFunc func(GetMeTagsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeTagsHandlerFunc) Handle(params GetMeTagsParams) middleware.Responder {
	return fn(params)
}

// GetMeTagsHandler interface for that can handle valid get me tags params
type GetMeTagsHandler interface {
	Handle(GetMeTagsParams) middleware.Responder
}

// NewGetMeTags creates a new http.Handler for the get me tags operation
func NewGetMeTags(ctx *middleware.Context, handler GetMeTagsHandler) *GetMeTags {
	return &GetMeTags{Context: ctx, Handler: handler}
}

/*GetMeTags swagger:route GET /me/tags me getMeTags

GetMeTags get me tags API

*/
type GetMeTags struct {
	Context *middleware.Context
	Handler GetMeTagsHandler
}

func (o *GetMeTags) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMeTagsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
