// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// GetMeOKCode is the HTTP code returned for type GetMeOK
const GetMeOKCode int = 200

/*GetMeOK OK

swagger:response getMeOK
*/
type GetMeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewGetMeOK creates GetMeOK with default headers values
func NewGetMeOK() *GetMeOK {

	return &GetMeOK{}
}

// WithPayload adds the payload to the get me o k response
func (o *GetMeOK) WithPayload(payload *models.Profile) *GetMeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get me o k response
func (o *GetMeOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
