// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostMeNotificationsHandlerFunc turns a function with the right signature into a post me notifications handler
type PostMeNotificationsHandlerFunc func(PostMeNotificationsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMeNotificationsHandlerFunc) Handle(params PostMeNotificationsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostMeNotificationsHandler interface for that can handle valid post me notifications params
type PostMeNotificationsHandler interface {
	Handle(PostMeNotificationsParams, interface{}) middleware.Responder
}

// NewPostMeNotifications creates a new http.Handler for the post me notifications operation
func NewPostMeNotifications(ctx *middleware.Context, handler PostMeNotificationsHandler) *PostMeNotifications {
	return &PostMeNotifications{Context: ctx, Handler: handler}
}

/*PostMeNotifications swagger:route POST /me/notifications me postMeNotifications

пометить уведомления как прочитанные

*/
type PostMeNotifications struct {
	Context *middleware.Context
	Handler PostMeNotificationsHandler
}

func (o *PostMeNotifications) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMeNotificationsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
