// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PutMeSettingsOKCode is the HTTP code returned for type PutMeSettingsOK
const PutMeSettingsOKCode int = 200

/*PutMeSettingsOK OK

swagger:response putMeSettingsOK
*/
type PutMeSettingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewPutMeSettingsOK creates PutMeSettingsOK with default headers values
func NewPutMeSettingsOK() *PutMeSettingsOK {

	return &PutMeSettingsOK{}
}

// WithPayload adds the payload to the put me settings o k response
func (o *PutMeSettingsOK) WithPayload(payload *models.Profile) *PutMeSettingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put me settings o k response
func (o *PutMeSettingsOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutMeSettingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
