// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PutMeSettingsNotificationsOKCode is the HTTP code returned for type PutMeSettingsNotificationsOK
const PutMeSettingsNotificationsOKCode int = 200

/*PutMeSettingsNotificationsOK OK

swagger:response putMeSettingsNotificationsOK
*/
type PutMeSettingsNotificationsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewPutMeSettingsNotificationsOK creates PutMeSettingsNotificationsOK with default headers values
func NewPutMeSettingsNotificationsOK() *PutMeSettingsNotificationsOK {

	return &PutMeSettingsNotificationsOK{}
}

// WithPayload adds the payload to the put me settings notifications o k response
func (o *PutMeSettingsNotificationsOK) WithPayload(payload *models.Profile) *PutMeSettingsNotificationsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put me settings notifications o k response
func (o *PutMeSettingsNotificationsOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutMeSettingsNotificationsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
