// Code generated by go-swagger; DO NOT EDIT.

package me

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PutMeSettingsPasswordOKCode is the HTTP code returned for type PutMeSettingsPasswordOK
const PutMeSettingsPasswordOKCode int = 200

/*PutMeSettingsPasswordOK OK

swagger:response putMeSettingsPasswordOK
*/
type PutMeSettingsPasswordOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewPutMeSettingsPasswordOK creates PutMeSettingsPasswordOK with default headers values
func NewPutMeSettingsPasswordOK() *PutMeSettingsPasswordOK {

	return &PutMeSettingsPasswordOK{}
}

// WithPayload adds the payload to the put me settings password o k response
func (o *PutMeSettingsPasswordOK) WithPayload(payload *models.Profile) *PutMeSettingsPasswordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put me settings password o k response
func (o *PutMeSettingsPasswordOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutMeSettingsPasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
