// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetTagsOKCode is the HTTP code returned for type GetTagsOK
const GetTagsOKCode int = 200

/*GetTagsOK OK

swagger:response getTagsOK
*/
type GetTagsOK struct {

	/*
	  In: Body
	*/
	Payload []string `json:"body,omitempty"`
}

// NewGetTagsOK creates GetTagsOK with default headers values
func NewGetTagsOK() *GetTagsOK {

	return &GetTagsOK{}
}

// WithPayload adds the payload to the get tags o k response
func (o *GetTagsOK) WithPayload(payload []string) *GetTagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tags o k response
func (o *GetTagsOK) SetPayload(payload []string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]string, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
