// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteProfilesUsernameStarHandlerFunc turns a function with the right signature into a delete profiles username star handler
type DeleteProfilesUsernameStarHandlerFunc func(DeleteProfilesUsernameStarParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProfilesUsernameStarHandlerFunc) Handle(params DeleteProfilesUsernameStarParams) middleware.Responder {
	return fn(params)
}

// DeleteProfilesUsernameStarHandler interface for that can handle valid delete profiles username star params
type DeleteProfilesUsernameStarHandler interface {
	Handle(DeleteProfilesUsernameStarParams) middleware.Responder
}

// NewDeleteProfilesUsernameStar creates a new http.Handler for the delete profiles username star operation
func NewDeleteProfilesUsernameStar(ctx *middleware.Context, handler DeleteProfilesUsernameStarHandler) *DeleteProfilesUsernameStar {
	return &DeleteProfilesUsernameStar{Context: ctx, Handler: handler}
}

/*DeleteProfilesUsernameStar swagger:route DELETE /profiles/{username}/star profile deleteProfilesUsernameStar

DeleteProfilesUsernameStar delete profiles username star API

*/
type DeleteProfilesUsernameStar struct {
	Context *middleware.Context
	Handler DeleteProfilesUsernameStarHandler
}

func (o *DeleteProfilesUsernameStar) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteProfilesUsernameStarParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
