// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetProfilesUsernameHandlerFunc turns a function with the right signature into a get profiles username handler
type GetProfilesUsernameHandlerFunc func(GetProfilesUsernameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProfilesUsernameHandlerFunc) Handle(params GetProfilesUsernameParams) middleware.Responder {
	return fn(params)
}

// GetProfilesUsernameHandler interface for that can handle valid get profiles username params
type GetProfilesUsernameHandler interface {
	Handle(GetProfilesUsernameParams) middleware.Responder
}

// NewGetProfilesUsername creates a new http.Handler for the get profiles username operation
func NewGetProfilesUsername(ctx *middleware.Context, handler GetProfilesUsernameHandler) *GetProfilesUsername {
	return &GetProfilesUsername{Context: ctx, Handler: handler}
}

/*GetProfilesUsername swagger:route GET /profiles/{username} profile getProfilesUsername

GetProfilesUsername get profiles username API

*/
type GetProfilesUsername struct {
	Context *middleware.Context
	Handler GetProfilesUsernameHandler
}

func (o *GetProfilesUsername) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProfilesUsernameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
