// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PostProfilesUsernameStarOKCode is the HTTP code returned for type PostProfilesUsernameStarOK
const PostProfilesUsernameStarOKCode int = 200

/*PostProfilesUsernameStarOK OK

swagger:response postProfilesUsernameStarOK
*/
type PostProfilesUsernameStarOK struct {

	/*
	  In: Body
	*/
	Payload *models.ProfileFull `json:"body,omitempty"`
}

// NewPostProfilesUsernameStarOK creates PostProfilesUsernameStarOK with default headers values
func NewPostProfilesUsernameStarOK() *PostProfilesUsernameStarOK {

	return &PostProfilesUsernameStarOK{}
}

// WithPayload adds the payload to the post profiles username star o k response
func (o *PostProfilesUsernameStarOK) WithPayload(payload *models.ProfileFull) *PostProfilesUsernameStarOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post profiles username star o k response
func (o *PostProfilesUsernameStarOK) SetPayload(payload *models.ProfileFull) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostProfilesUsernameStarOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
