// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostProfilesUsernameStarHandlerFunc turns a function with the right signature into a post profiles username star handler
type PostProfilesUsernameStarHandlerFunc func(PostProfilesUsernameStarParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostProfilesUsernameStarHandlerFunc) Handle(params PostProfilesUsernameStarParams) middleware.Responder {
	return fn(params)
}

// PostProfilesUsernameStarHandler interface for that can handle valid post profiles username star params
type PostProfilesUsernameStarHandler interface {
	Handle(PostProfilesUsernameStarParams) middleware.Responder
}

// NewPostProfilesUsernameStar creates a new http.Handler for the post profiles username star operation
func NewPostProfilesUsernameStar(ctx *middleware.Context, handler PostProfilesUsernameStarHandler) *PostProfilesUsernameStar {
	return &PostProfilesUsernameStar{Context: ctx, Handler: handler}
}

/*PostProfilesUsernameStar swagger:route POST /profiles/{username}/star profile postProfilesUsernameStar

PostProfilesUsernameStar post profiles username star API

*/
type PostProfilesUsernameStar struct {
	Context *middleware.Context
	Handler PostProfilesUsernameStarHandler
}

func (o *PostProfilesUsernameStar) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostProfilesUsernameStarParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
