// Code generated by go-swagger; DO NOT EDIT.

package profiles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PutProfilesOKCode is the HTTP code returned for type PutProfilesOK
const PutProfilesOKCode int = 200

/*PutProfilesOK OK

swagger:response putProfilesOK
*/
type PutProfilesOK struct {

	/*
	  In: Body
	*/
	Payload *models.Profile `json:"body,omitempty"`
}

// NewPutProfilesOK creates PutProfilesOK with default headers values
func NewPutProfilesOK() *PutProfilesOK {

	return &PutProfilesOK{}
}

// WithPayload adds the payload to the put profiles o k response
func (o *PutProfilesOK) WithPayload(payload *models.Profile) *PutProfilesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put profiles o k response
func (o *PutProfilesOK) SetPayload(payload *models.Profile) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutProfilesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
