// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteArticlesArticleIDVoteHandlerFunc turns a function with the right signature into a delete articles article ID vote handler
type DeleteArticlesArticleIDVoteHandlerFunc func(DeleteArticlesArticleIDVoteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteArticlesArticleIDVoteHandlerFunc) Handle(params DeleteArticlesArticleIDVoteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteArticlesArticleIDVoteHandler interface for that can handle valid delete articles article ID vote params
type DeleteArticlesArticleIDVoteHandler interface {
	Handle(DeleteArticlesArticleIDVoteParams, interface{}) middleware.Responder
}

// NewDeleteArticlesArticleIDVote creates a new http.Handler for the delete articles article ID vote operation
func NewDeleteArticlesArticleIDVote(ctx *middleware.Context, handler DeleteArticlesArticleIDVoteHandler) *DeleteArticlesArticleIDVote {
	return &DeleteArticlesArticleIDVote{Context: ctx, Handler: handler}
}

/*DeleteArticlesArticleIDVote swagger:route DELETE /articles/{articleId}/vote articles deleteArticlesArticleIdVote

DeleteArticlesArticleIDVote delete articles article ID vote API

*/
type DeleteArticlesArticleIDVote struct {
	Context *middleware.Context
	Handler DeleteArticlesArticleIDVoteHandler
}

func (o *DeleteArticlesArticleIDVote) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteArticlesArticleIDVoteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
