// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteArticlesArticleIDVoteOKCode is the HTTP code returned for type DeleteArticlesArticleIDVoteOK
const DeleteArticlesArticleIDVoteOKCode int = 200

/*DeleteArticlesArticleIDVoteOK OK

swagger:response deleteArticlesArticleIdVoteOK
*/
type DeleteArticlesArticleIDVoteOK struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewDeleteArticlesArticleIDVoteOK creates DeleteArticlesArticleIDVoteOK with default headers values
func NewDeleteArticlesArticleIDVoteOK() *DeleteArticlesArticleIDVoteOK {

	return &DeleteArticlesArticleIDVoteOK{}
}

// WithPayload adds the payload to the delete articles article Id vote o k response
func (o *DeleteArticlesArticleIDVoteOK) WithPayload(payload int64) *DeleteArticlesArticleIDVoteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete articles article Id vote o k response
func (o *DeleteArticlesArticleIDVoteOK) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteArticlesArticleIDVoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
