// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetArticlesParams creates a new GetArticlesParams object
// with the default values initialized.
func NewGetArticlesParams() GetArticlesParams {

	var (
		// initialize parameters with default values

		followedDefault = bool(false)
		limitDefault    = uint64(20)
		offsetDefault   = uint64(0)
		sortByDefault   = string("date")
	)

	return GetArticlesParams{
		Followed: &followedDefault,

		Limit: limitDefault,

		Offset: offsetDefault,

		SortBy: sortByDefault,
	}
}

// GetArticlesParams contains all the bound params for the get articles operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetArticles
type GetArticlesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	  Default: false
	*/
	Followed *bool
	/*The numbers of items to return (default is 20)
	  In: query
	  Default: 20
	*/
	Limit uint64
	/*The number of items to skip before starting to collect the result set (default is 0)
	  In: query
	  Default: 0
	*/
	Offset uint64
	/*
	  Required: true
	  In: query
	  Default: "date"
	*/
	SortBy string
	/*
	  In: query
	*/
	Tag *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetArticlesParams() beforehand.
func (o *GetArticlesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFollowed, qhkFollowed, _ := qs.GetOK("followed")
	if err := o.bindFollowed(qFollowed, qhkFollowed, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qSortBy, qhkSortBy, _ := qs.GetOK("sortBy")
	if err := o.bindSortBy(qSortBy, qhkSortBy, route.Formats); err != nil {
		res = append(res, err)
	}

	qTag, qhkTag, _ := qs.GetOK("tag")
	if err := o.bindTag(qTag, qhkTag, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFollowed binds and validates parameter Followed from query.
func (o *GetArticlesParams) bindFollowed(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetArticlesParams()
		return nil
	}

	value, err := swag.ConvertBool(raw)
	if err != nil {
		return errors.InvalidType("followed", "query", "bool", raw)
	}
	o.Followed = &value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetArticlesParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: true
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetArticlesParams()
		return nil
	}

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "uint64", raw)
	}
	o.Limit = value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetArticlesParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: true
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetArticlesParams()
		return nil
	}

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "uint64", raw)
	}
	o.Offset = value

	return nil
}

// bindSortBy binds and validates parameter SortBy from query.
func (o *GetArticlesParams) bindSortBy(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("sortBy", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("sortBy", "query", raw); err != nil {
		return err
	}

	o.SortBy = raw

	if err := o.validateSortBy(formats); err != nil {
		return err
	}

	return nil
}

// validateSortBy carries on validations for parameter SortBy
func (o *GetArticlesParams) validateSortBy(formats strfmt.Registry) error {

	if err := validate.Enum("sortBy", "query", o.SortBy, []interface{}{"date", "comments", "rating"}); err != nil {
		return err
	}

	return nil
}

// bindTag binds and validates parameter Tag from query.
func (o *GetArticlesParams) bindTag(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Tag = &raw

	return nil
}
