// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// GetArticlesOKCode is the HTTP code returned for type GetArticlesOK
const GetArticlesOKCode int = 200

/*GetArticlesOK OK

swagger:response getArticlesOK
*/
type GetArticlesOK struct {

	/*
	  In: Body
	*/
	Payload models.Articles `json:"body,omitempty"`
}

// NewGetArticlesOK creates GetArticlesOK with default headers values
func NewGetArticlesOK() *GetArticlesOK {

	return &GetArticlesOK{}
}

// WithPayload adds the payload to the get articles o k response
func (o *GetArticlesOK) WithPayload(payload models.Articles) *GetArticlesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles o k response
func (o *GetArticlesOK) SetPayload(payload models.Articles) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Articles{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
