// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetFeedsFeedIDArticlesHandlerFunc turns a function with the right signature into a get feeds feed ID articles handler
type GetFeedsFeedIDArticlesHandlerFunc func(GetFeedsFeedIDArticlesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFeedsFeedIDArticlesHandlerFunc) Handle(params GetFeedsFeedIDArticlesParams) middleware.Responder {
	return fn(params)
}

// GetFeedsFeedIDArticlesHandler interface for that can handle valid get feeds feed ID articles params
type GetFeedsFeedIDArticlesHandler interface {
	Handle(GetFeedsFeedIDArticlesParams) middleware.Responder
}

// NewGetFeedsFeedIDArticles creates a new http.Handler for the get feeds feed ID articles operation
func NewGetFeedsFeedIDArticles(ctx *middleware.Context, handler GetFeedsFeedIDArticlesHandler) *GetFeedsFeedIDArticles {
	return &GetFeedsFeedIDArticles{Context: ctx, Handler: handler}
}

/*GetFeedsFeedIDArticles swagger:route GET /feeds/{feedId}/articles articles getFeedsFeedIdArticles

GetFeedsFeedIDArticles get feeds feed ID articles API

*/
type GetFeedsFeedIDArticles struct {
	Context *middleware.Context
	Handler GetFeedsFeedIDArticlesHandler
}

func (o *GetFeedsFeedIDArticles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFeedsFeedIDArticlesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
