// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetArticlesArticleIDHandlerFunc turns a function with the right signature into a get articles article ID handler
type GetArticlesArticleIDHandlerFunc func(GetArticlesArticleIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetArticlesArticleIDHandlerFunc) Handle(params GetArticlesArticleIDParams) middleware.Responder {
	return fn(params)
}

// GetArticlesArticleIDHandler interface for that can handle valid get articles article ID params
type GetArticlesArticleIDHandler interface {
	Handle(GetArticlesArticleIDParams) middleware.Responder
}

// NewGetArticlesArticleID creates a new http.Handler for the get articles article ID operation
func NewGetArticlesArticleID(ctx *middleware.Context, handler GetArticlesArticleIDHandler) *GetArticlesArticleID {
	return &GetArticlesArticleID{Context: ctx, Handler: handler}
}

/*GetArticlesArticleID swagger:route GET /articles/{articleId} articles getArticlesArticleId

GetArticlesArticleID get articles article ID API

*/
type GetArticlesArticleID struct {
	Context *middleware.Context
	Handler GetArticlesArticleIDHandler
}

func (o *GetArticlesArticleID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetArticlesArticleIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
