// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetFeedsFeedIDArticlesParams creates a new GetFeedsFeedIDArticlesParams object
// with the default values initialized.
func NewGetFeedsFeedIDArticlesParams() GetFeedsFeedIDArticlesParams {

	var (
		// initialize parameters with default values

		limitDefault  = uint64(20)
		offsetDefault = uint64(0)
	)

	return GetFeedsFeedIDArticlesParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetFeedsFeedIDArticlesParams contains all the bound params for the get feeds feed ID articles operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetFeedsFeedIDArticles
type GetFeedsFeedIDArticlesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	FeedID uint64
	/*Limit number of articles (default is 20)
	  In: query
	  Default: 20
	*/
	Limit *uint64
	/*Offset/skip number of articles (default is 0)
	  In: query
	  Default: 0
	*/
	Offset *uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFeedsFeedIDArticlesParams() beforehand.
func (o *GetFeedsFeedIDArticlesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rFeedID, rhkFeedID, _ := route.Params.GetOK("feedId")
	if err := o.bindFeedID(rFeedID, rhkFeedID, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFeedID binds and validates parameter FeedID from path.
func (o *GetFeedsFeedIDArticlesParams) bindFeedID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("feedId", "path", "uint64", raw)
	}
	o.FeedID = value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetFeedsFeedIDArticlesParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetFeedsFeedIDArticlesParams()
		return nil
	}

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "uint64", raw)
	}
	o.Limit = &value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetFeedsFeedIDArticlesParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetFeedsFeedIDArticlesParams()
		return nil
	}

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "uint64", raw)
	}
	o.Offset = &value

	return nil
}
