// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PostArticlesOKCode is the HTTP code returned for type PostArticlesOK
const PostArticlesOKCode int = 200

/*PostArticlesOK OK

swagger:response postArticlesOK
*/
type PostArticlesOK struct {

	/*
	  In: Body
	*/
	Payload *models.Article `json:"body,omitempty"`
}

// NewPostArticlesOK creates PostArticlesOK with default headers values
func NewPostArticlesOK() *PostArticlesOK {

	return &PostArticlesOK{}
}

// WithPayload adds the payload to the post articles o k response
func (o *PostArticlesOK) WithPayload(payload *models.Article) *PostArticlesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post articles o k response
func (o *PostArticlesOK) SetPayload(payload *models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostArticlesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
