// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostArticlesArticleIDVoteOKCode is the HTTP code returned for type PostArticlesArticleIDVoteOK
const PostArticlesArticleIDVoteOKCode int = 200

/*PostArticlesArticleIDVoteOK OK

swagger:response postArticlesArticleIdVoteOK
*/
type PostArticlesArticleIDVoteOK struct {

	/*
	  In: Body
	*/
	Payload int64 `json:"body,omitempty"`
}

// NewPostArticlesArticleIDVoteOK creates PostArticlesArticleIDVoteOK with default headers values
func NewPostArticlesArticleIDVoteOK() *PostArticlesArticleIDVoteOK {

	return &PostArticlesArticleIDVoteOK{}
}

// WithPayload adds the payload to the post articles article Id vote o k response
func (o *PostArticlesArticleIDVoteOK) WithPayload(payload int64) *PostArticlesArticleIDVoteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post articles article Id vote o k response
func (o *PostArticlesArticleIDVoteOK) SetPayload(payload int64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostArticlesArticleIDVoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
