// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostArticlesHandlerFunc turns a function with the right signature into a post articles handler
type PostArticlesHandlerFunc func(PostArticlesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostArticlesHandlerFunc) Handle(params PostArticlesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostArticlesHandler interface for that can handle valid post articles params
type PostArticlesHandler interface {
	Handle(PostArticlesParams, interface{}) middleware.Responder
}

// NewPostArticles creates a new http.Handler for the post articles operation
func NewPostArticles(ctx *middleware.Context, handler PostArticlesHandler) *PostArticles {
	return &PostArticles{Context: ctx, Handler: handler}
}

/*PostArticles swagger:route POST /articles articles postArticles

PostArticles post articles API

*/
type PostArticles struct {
	Context *middleware.Context
	Handler PostArticlesHandler
}

func (o *PostArticles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostArticlesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
