// Code generated by go-swagger; DO NOT EDIT.

package articles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// PutArticlesArticleIDOKCode is the HTTP code returned for type PutArticlesArticleIDOK
const PutArticlesArticleIDOKCode int = 200

/*PutArticlesArticleIDOK OK

swagger:response putArticlesArticleIdOK
*/
type PutArticlesArticleIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Article `json:"body,omitempty"`
}

// NewPutArticlesArticleIDOK creates PutArticlesArticleIDOK with default headers values
func NewPutArticlesArticleIDOK() *PutArticlesArticleIDOK {

	return &PutArticlesArticleIDOK{}
}

// WithPayload adds the payload to the put articles article Id o k response
func (o *PutArticlesArticleIDOK) WithPayload(payload *models.Article) *PutArticlesArticleIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put articles article Id o k response
func (o *PutArticlesArticleIDOK) SetPayload(payload *models.Article) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutArticlesArticleIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
