// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// DeleteCommentsCommentIDOKCode is the HTTP code returned for type DeleteCommentsCommentIDOK
const DeleteCommentsCommentIDOKCode int = 200

/*DeleteCommentsCommentIDOK OK

swagger:response deleteCommentsCommentIdOK
*/
type DeleteCommentsCommentIDOK struct {

	/*
	  In: Body
	*/
	Payload models.Articles `json:"body,omitempty"`
}

// NewDeleteCommentsCommentIDOK creates DeleteCommentsCommentIDOK with default headers values
func NewDeleteCommentsCommentIDOK() *DeleteCommentsCommentIDOK {

	return &DeleteCommentsCommentIDOK{}
}

// WithPayload adds the payload to the delete comments comment Id o k response
func (o *DeleteCommentsCommentIDOK) WithPayload(payload models.Articles) *DeleteCommentsCommentIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete comments comment Id o k response
func (o *DeleteCommentsCommentIDOK) SetPayload(payload models.Articles) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteCommentsCommentIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Articles{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
