// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteCommentsCommentIDHandlerFunc turns a function with the right signature into a delete comments comment ID handler
type DeleteCommentsCommentIDHandlerFunc func(DeleteCommentsCommentIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteCommentsCommentIDHandlerFunc) Handle(params DeleteCommentsCommentIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteCommentsCommentIDHandler interface for that can handle valid delete comments comment ID params
type DeleteCommentsCommentIDHandler interface {
	Handle(DeleteCommentsCommentIDParams, interface{}) middleware.Responder
}

// NewDeleteCommentsCommentID creates a new http.Handler for the delete comments comment ID operation
func NewDeleteCommentsCommentID(ctx *middleware.Context, handler DeleteCommentsCommentIDHandler) *DeleteCommentsCommentID {
	return &DeleteCommentsCommentID{Context: ctx, Handler: handler}
}

/*DeleteCommentsCommentID swagger:route DELETE /comments/{commentId} comments deleteCommentsCommentId

DeleteCommentsCommentID delete comments comment ID API

*/
type DeleteCommentsCommentID struct {
	Context *middleware.Context
	Handler DeleteCommentsCommentIDHandler
}

func (o *DeleteCommentsCommentID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteCommentsCommentIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
