// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCommentsCommentIDCommentsParams creates a new GetCommentsCommentIDCommentsParams object
// with the default values initialized.
func NewGetCommentsCommentIDCommentsParams() GetCommentsCommentIDCommentsParams {

	var (
		// initialize parameters with default values

		limitDefault  = uint64(20)
		offsetDefault = uint64(0)
	)

	return GetCommentsCommentIDCommentsParams{
		Limit: limitDefault,

		Offset: offsetDefault,
	}
}

// GetCommentsCommentIDCommentsParams contains all the bound params for the get comments comment ID comments operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetCommentsCommentIDComments
type GetCommentsCommentIDCommentsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	CommentID int64
	/*The numbers of items to return (default is 20)
	  In: query
	  Default: 20
	*/
	Limit uint64
	/*The number of items to skip before starting to collect the result set (default is 0)
	  In: query
	  Default: 0
	*/
	Offset uint64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCommentsCommentIDCommentsParams() beforehand.
func (o *GetCommentsCommentIDCommentsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	rCommentID, rhkCommentID, _ := route.Params.GetOK("commentId")
	if err := o.bindCommentID(rCommentID, rhkCommentID, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCommentID binds and validates parameter CommentID from path.
func (o *GetCommentsCommentIDCommentsParams) bindCommentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("commentId", "path", "int64", raw)
	}
	o.CommentID = value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetCommentsCommentIDCommentsParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: true
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetCommentsCommentIDCommentsParams()
		return nil
	}

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "uint64", raw)
	}
	o.Limit = value

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetCommentsCommentIDCommentsParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: true
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetCommentsCommentIDCommentsParams()
		return nil
	}

	value, err := swag.ConvertUint64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "uint64", raw)
	}
	o.Offset = value

	return nil
}
