// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// GetCommentsCommentIDCommentsOKCode is the HTTP code returned for type GetCommentsCommentIDCommentsOK
const GetCommentsCommentIDCommentsOKCode int = 200

/*GetCommentsCommentIDCommentsOK OK

swagger:response getCommentsCommentIdCommentsOK
*/
type GetCommentsCommentIDCommentsOK struct {

	/*
	  In: Body
	*/
	Payload models.Comments `json:"body,omitempty"`
}

// NewGetCommentsCommentIDCommentsOK creates GetCommentsCommentIDCommentsOK with default headers values
func NewGetCommentsCommentIDCommentsOK() *GetCommentsCommentIDCommentsOK {

	return &GetCommentsCommentIDCommentsOK{}
}

// WithPayload adds the payload to the get comments comment Id comments o k response
func (o *GetCommentsCommentIDCommentsOK) WithPayload(payload models.Comments) *GetCommentsCommentIDCommentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments comment Id comments o k response
func (o *GetCommentsCommentIDCommentsOK) SetPayload(payload models.Comments) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsCommentIDCommentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Comments{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
