// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCommentsCommentIDCommentsHandlerFunc turns a function with the right signature into a get comments comment ID comments handler
type GetCommentsCommentIDCommentsHandlerFunc func(GetCommentsCommentIDCommentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommentsCommentIDCommentsHandlerFunc) Handle(params GetCommentsCommentIDCommentsParams) middleware.Responder {
	return fn(params)
}

// GetCommentsCommentIDCommentsHandler interface for that can handle valid get comments comment ID comments params
type GetCommentsCommentIDCommentsHandler interface {
	Handle(GetCommentsCommentIDCommentsParams) middleware.Responder
}

// NewGetCommentsCommentIDComments creates a new http.Handler for the get comments comment ID comments operation
func NewGetCommentsCommentIDComments(ctx *middleware.Context, handler GetCommentsCommentIDCommentsHandler) *GetCommentsCommentIDComments {
	return &GetCommentsCommentIDComments{Context: ctx, Handler: handler}
}

/*GetCommentsCommentIDComments swagger:route GET /comments/{commentId}/comments comments getCommentsCommentIdComments

GetCommentsCommentIDComments get comments comment ID comments API

*/
type GetCommentsCommentIDComments struct {
	Context *middleware.Context
	Handler GetCommentsCommentIDCommentsHandler
}

func (o *GetCommentsCommentIDComments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCommentsCommentIDCommentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
