// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetArticlesArticleIDCommentsURL generates an URL for the get articles article ID comments operation
type GetArticlesArticleIDCommentsURL struct {
	ArticleID uint64

	Limit  uint64
	Offset uint64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetArticlesArticleIDCommentsURL) WithBasePath(bp string) *GetArticlesArticleIDCommentsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetArticlesArticleIDCommentsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetArticlesArticleIDCommentsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/articles/{articleId}/comments"

	articleID := swag.FormatUint64(o.ArticleID)
	if articleID != "" {
		_path = strings.Replace(_path, "{articleId}", articleID, -1)
	} else {
		return nil, errors.New("articleId is required on GetArticlesArticleIDCommentsURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	limitQ := swag.FormatUint64(o.Limit)
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	offsetQ := swag.FormatUint64(o.Offset)
	if offsetQ != "" {
		qs.Set("offset", offsetQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetArticlesArticleIDCommentsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetArticlesArticleIDCommentsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetArticlesArticleIDCommentsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetArticlesArticleIDCommentsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetArticlesArticleIDCommentsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetArticlesArticleIDCommentsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
