// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "morg/models"
)

// GetArticlesArticleIDCommentsOKCode is the HTTP code returned for type GetArticlesArticleIDCommentsOK
const GetArticlesArticleIDCommentsOKCode int = 200

/*GetArticlesArticleIDCommentsOK OK

swagger:response getArticlesArticleIdCommentsOK
*/
type GetArticlesArticleIDCommentsOK struct {

	/*
	  In: Body
	*/
	Payload models.Comments `json:"body,omitempty"`
}

// NewGetArticlesArticleIDCommentsOK creates GetArticlesArticleIDCommentsOK with default headers values
func NewGetArticlesArticleIDCommentsOK() *GetArticlesArticleIDCommentsOK {

	return &GetArticlesArticleIDCommentsOK{}
}

// WithPayload adds the payload to the get articles article Id comments o k response
func (o *GetArticlesArticleIDCommentsOK) WithPayload(payload models.Comments) *GetArticlesArticleIDCommentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get articles article Id comments o k response
func (o *GetArticlesArticleIDCommentsOK) SetPayload(payload models.Comments) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetArticlesArticleIDCommentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Comments{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
