// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// PostCommentsCommentIDVoteURL generates an URL for the post comments comment ID vote operation
type PostCommentsCommentIDVoteURL struct {
	CommentID uint64

	Vote int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostCommentsCommentIDVoteURL) WithBasePath(bp string) *PostCommentsCommentIDVoteURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *PostCommentsCommentIDVoteURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *PostCommentsCommentIDVoteURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/comments/{commentId}/vote"

	commentID := swag.FormatUint64(o.CommentID)
	if commentID != "" {
		_path = strings.Replace(_path, "{commentId}", commentID, -1)
	} else {
		return nil, errors.New("commentId is required on PostCommentsCommentIDVoteURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	voteQ := swag.FormatInt64(o.Vote)
	if voteQ != "" {
		qs.Set("vote", voteQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *PostCommentsCommentIDVoteURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *PostCommentsCommentIDVoteURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *PostCommentsCommentIDVoteURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on PostCommentsCommentIDVoteURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on PostCommentsCommentIDVoteURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *PostCommentsCommentIDVoteURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
