// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostCommentsCommentIDVoteHandlerFunc turns a function with the right signature into a post comments comment ID vote handler
type PostCommentsCommentIDVoteHandlerFunc func(PostCommentsCommentIDVoteParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCommentsCommentIDVoteHandlerFunc) Handle(params PostCommentsCommentIDVoteParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostCommentsCommentIDVoteHandler interface for that can handle valid post comments comment ID vote params
type PostCommentsCommentIDVoteHandler interface {
	Handle(PostCommentsCommentIDVoteParams, interface{}) middleware.Responder
}

// NewPostCommentsCommentIDVote creates a new http.Handler for the post comments comment ID vote operation
func NewPostCommentsCommentIDVote(ctx *middleware.Context, handler PostCommentsCommentIDVoteHandler) *PostCommentsCommentIDVote {
	return &PostCommentsCommentIDVote{Context: ctx, Handler: handler}
}

/*PostCommentsCommentIDVote swagger:route POST /comments/{commentId}/vote comments postCommentsCommentIdVote

PostCommentsCommentIDVote post comments comment ID vote API

*/
type PostCommentsCommentIDVote struct {
	Context *middleware.Context
	Handler PostCommentsCommentIDVoteHandler
}

func (o *PostCommentsCommentIDVote) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCommentsCommentIDVoteParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
