// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostArticlesArticleIDCommentsHandlerFunc turns a function with the right signature into a post articles article ID comments handler
type PostArticlesArticleIDCommentsHandlerFunc func(PostArticlesArticleIDCommentsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostArticlesArticleIDCommentsHandlerFunc) Handle(params PostArticlesArticleIDCommentsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostArticlesArticleIDCommentsHandler interface for that can handle valid post articles article ID comments params
type PostArticlesArticleIDCommentsHandler interface {
	Handle(PostArticlesArticleIDCommentsParams, interface{}) middleware.Responder
}

// NewPostArticlesArticleIDComments creates a new http.Handler for the post articles article ID comments operation
func NewPostArticlesArticleIDComments(ctx *middleware.Context, handler PostArticlesArticleIDCommentsHandler) *PostArticlesArticleIDComments {
	return &PostArticlesArticleIDComments{Context: ctx, Handler: handler}
}

/*PostArticlesArticleIDComments swagger:route POST /articles/{articleId}/comments comments postArticlesArticleIdComments

PostArticlesArticleIDComments post articles article ID comments API

*/
type PostArticlesArticleIDComments struct {
	Context *middleware.Context
	Handler PostArticlesArticleIDCommentsHandler
}

func (o *PostArticlesArticleIDComments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostArticlesArticleIDCommentsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
