// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostCommentsHandlerFunc turns a function with the right signature into a post comments handler
type PostCommentsHandlerFunc func(PostCommentsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostCommentsHandlerFunc) Handle(params PostCommentsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostCommentsHandler interface for that can handle valid post comments params
type PostCommentsHandler interface {
	Handle(PostCommentsParams, interface{}) middleware.Responder
}

// NewPostComments creates a new http.Handler for the post comments operation
func NewPostComments(ctx *middleware.Context, handler PostCommentsHandler) *PostComments {
	return &PostComments{Context: ctx, Handler: handler}
}

/*PostComments swagger:route POST /comments comments postComments

PostComments post comments API

*/
type PostComments struct {
	Context *middleware.Context
	Handler PostCommentsHandler
}

func (o *PostComments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostCommentsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
