// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CommentCreate comment create
// swagger:model CommentCreate
type CommentCreate struct {

	// article Id
	// Required: true
	ArticleID *uint64 `json:"articleId"`

	// body
	// Required: true
	Body *string `json:"body"`

	// id коментария, на котрый отвечает
	ParentID uint64 `json:"parentId,omitempty"`
}

// Validate validates this comment create
func (m *CommentCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArticleID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CommentCreate) validateArticleID(formats strfmt.Registry) error {

	if err := validate.Required("articleId", "body", m.ArticleID); err != nil {
		return err
	}

	return nil
}

func (m *CommentCreate) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("body", "body", m.Body); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CommentCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommentCreate) UnmarshalBinary(b []byte) error {
	var res CommentCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
