// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NotificationSettings notification settings
// swagger:model NotificationSettings
type NotificationSettings struct {

	// comments
	// Required: true
	Comments *bool `json:"comments"`

	// follows
	// Required: true
	Follows *bool `json:"follows"`

	// requests
	// Required: true
	Requests *bool `json:"requests"`
}

// Validate validates this notification settings
func (m *NotificationSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComments(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFollows(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequests(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NotificationSettings) validateComments(formats strfmt.Registry) error {

	if err := validate.Required("comments", "body", m.Comments); err != nil {
		return err
	}

	return nil
}

func (m *NotificationSettings) validateFollows(formats strfmt.Registry) error {

	if err := validate.Required("follows", "body", m.Follows); err != nil {
		return err
	}

	return nil
}

func (m *NotificationSettings) validateRequests(formats strfmt.Registry) error {

	if err := validate.Required("requests", "body", m.Requests); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NotificationSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationSettings) UnmarshalBinary(b []byte) error {
	var res NotificationSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
