// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PasswordUpdate password update
// swagger:model PasswordUpdate
type PasswordUpdate struct {

	// new password
	// Required: true
	// Min Length: 6
	NewPassword *string `json:"newPassword"`

	// old password
	// Required: true
	OldPassword *string `json:"oldPassword"`
}

// Validate validates this password update
func (m *PasswordUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewPassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOldPassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PasswordUpdate) validateNewPassword(formats strfmt.Registry) error {

	if err := validate.Required("newPassword", "body", m.NewPassword); err != nil {
		return err
	}

	if err := validate.MinLength("newPassword", "body", string(*m.NewPassword), 6); err != nil {
		return err
	}

	return nil
}

func (m *PasswordUpdate) validateOldPassword(formats strfmt.Registry) error {

	if err := validate.Required("oldPassword", "body", m.OldPassword); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PasswordUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PasswordUpdate) UnmarshalBinary(b []byte) error {
	var res PasswordUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
